### ISSUE TITLE
Will This Work with React Native?

### ISSUE THREAD

**Issue by quadsurf** [noahfeder/react-jwplayer#1]
If yes, do you have any guidance on how I can make the conversion from React to ReactNative?

**Comment by noahfeder** [comment]
Unfortunately, since we're using JWPlayer's iframe embed method, this won't work in React Native. JWPlayer does have [iOS and Android SDKs](https://www.jwplayer.com/video-solutions/mobile-sdk/) that should be usable with React Native, but I have not used them myself.
